name: CI
on:
  push:
  pull_request: 
  schedule:
    - cron: "30 3 * * WED" # every Wednesday at 3:30 AM, only main branch

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.7.2
    
jobs:
  compile:
    name: Compile
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Get all tags for correct version determination
      working-directory:  ${{ github.workspace }}
      run: |
          git fetch --all --tags -f
    - name: Install-Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        install-deps: 'true'

    - name:  Download JOM
      uses: suisei-cn/actions-download-file@v1
      with:
          url:    http://download.qt.io/official_releases/jom/jom.zip
          target: ${{ runner.temp }}\

    - name: Unzip JOM
      working-directory: ${{ runner.temp }}
      run:  |
            7z x jom.zip -ojom
      
    - name: Create build directory
      run:  mkdir ${{ runner.temp }}\build

    - name: Build
      working-directory: ${{ runner.temp }}\build
      run:  |
            qmake -r ${{ env.SOURCE_DIR }}\planets-qml.pro
            ${{ runner.temp }}\jom\jom -j2
            cd release
